### ISSUE TITLE
python: can't open file 'scripts/Haplotype.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by mictadlo** [jclev-uga/SWEEP#2]
Hi,
SWEEP.pl caused `python: can't open file 'scripts/Haplotype.py': [Errno 2] No such file or directory`

Best wishes,

Mic

**Comment by jclev-uga** [comment]
Thanks for letting me know.  I fixed it.  Essentially in the version I zipped for myself I had the scripts in a directory named scripts/.  In the github distro I can't do subfolders so I needed to take that out of SWEEP.pl.

You can download the fixed version, fix SWEEP.pl to take out scripts/ in the command calls, or just put all the files *.py in a directory called scripts within the SWEEP directory.

cheers

Josh

**Comment by mictadlo** [comment]
Thank you.
