### ISSUE TITLE
SWEEP without bam-files

### ISSUE THREAD

**Issue by milenazilena** [jclev-uga/SWEEP#4]
Hello there!
Is it possible to use SWEEP only with an existing .vcf file without its bam-files? 

This is my input:
perl SWEEP/SWEEP.pl -o outputarabidopsis.vcf -s 1 -d 5 -r 0.25 -vcf SWEEP/NEW_SNV_raw_REF_DH05_Bnapus_UGI_genome_GENO_multisample.vcf -num_genotypes 52

and this is my error:
CMD: python SWEEP/vcf.py SWEEP/NEW_SNV_raw_REF_DH05_Bnapus_UGI_genome_GENO_multisample.vcf filter.vcf 52 100
Traceback (most recent call last):
  File "SWEEP/vcf.py", line 115, in <module>
    main()
  File "SWEEP/vcf.py", line 15, in main
    for line in infile:
  File "/home/milenazilena/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Error, cmd: python SWEEP/vcf.py SWEEP/NEW_SNV_raw_REF_DH05_Bnapus_UGI_genome_GENO_multisample.vcf filter.vcf 52 100 died with ret 256 at SWEEP/SWEEP.pl line 148.

Sorry, i'm very new to programming. But maybe you can help me to fix this issue :)

Cheers, Milena

**Comment by jclev-uga** [comment]
Yes sure.  Just run the python script in the scripts/ folder call Haplotype.py.  That one takes the vcf file and filters it without using any informaiton in the bam files.  If you have any trouble with usage let me know.


Josh

________________________________

**Comment by milenazilena** [comment]
Thanks a lot for your rapid reply!

My problems are these two lines I guess. 
 num = int(sys.argv[3])
 win = int(sys.argv[4])

What should be the Input there? And do I need and tabbixed vcf?

My error:
python SWEEP/Haplotype.py SWEEP/NEW_SNV_raw_REF_DH05_Bnapus_UGI_genome_GENO_multisample.vcf SWEEP/output.txt
Traceback (most recent call last):
  File "SWEEP/Haplotype.py", line 110, in <module>
    main()
  File "SWEEP/Haplotype.py", line 8, in main
    num = int(sys.argv[3])
IndexError: list index out of range

Greetings, Milena
